datos <- read.csv("naftrac-2017-GA.csv")
plot(datos$Adj.Close, type = "l", main = "Rojo = Venta \n Blue = Compra \n (Momentos de ejecución)")
indices_buy <- which(datos$Clase == 1)
indices_sell <- which(datos$Clase == -1)
points(x = indices_buy + 1, datos$Adj.Close[indices_buy + 1], col = "blue", pch = 25, cex = 1.5, lwd = 2)
points(x = indices_sell + 1, datos$Adj.Close[indices_sell + 1], col = "red", pch = 25, cex = 1.5, lwd = 2)
points(x = length(datos$Adj.Close), y = datos$Adj.Close[length(datos$Adj.Close)], col = "red", pch = 16, cex = 1.5)
